### ISSUE TITLE
File download

### ISSUE THREAD

**Issue by Zeluok** [lukasa1993/scp-client#10]
please support local download! (-r for directories)

**Comment by lukasa1993** [comment]
@Zeluok hey, if by local you mean like iPhone this is not intended for it, i made this to manage file on server. if you need to map your ssh server to your iPhone [Termius](https://apps.apple.com/ge/app/termius-terminal-ssh-client/id549039908) has is covered pretty well and its free

**Comment by Zeluok** [comment]
oh you're right, just tried it. thank you
