### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by Zeluok** [lukasa1993/scp-client#11]
please support file upload when files are shared with the app (?)

<img src="https://user-images.githubusercontent.com/85944177/211330536-ae31fb1a-6938-4f61-9f73-d3f492d20b1e.png" width="200" />

**Comment by lukasa1993** [comment]
@Zeluok same as https://github.com/lukasa1993/scp-client/issues/10#issuecomment-1375698296 not intended to connect iPhone local files to ssh, that case is well established and i personally use termius as well
