### ISSUE TITLE
View or Edit not working on GLiNET etc/config/wireless

### ISSUE THREAD

**Issue by jksmurf** [lukasa1993/scp-client#12]
Hi, pretty low tech user here so bear with me. I normally use WinSCP to very occasionally edit files on my GLinet Travel Router for troubleshooting but needed an iOS version.

Your SCP App seems to be a simple one that at least works to view the folders. However it fails to view or edit the file I need to edit, see pics attached with error messages. Thanks 🙏!

![71783BA6-0DFE-4A13-9805-9D74AD5BCC69](https://user-images.githubusercontent.com/23158634/220020502-2526c0a1-d651-4e2b-a21d-b3b468988241.png)

![960EEC0F-FFE9-44F2-AD79-49C7ADF71B5B](https://user-images.githubusercontent.com/23158634/220020509-78d32ed3-eb3e-4c88-8414-b94a6ab85044.jpeg)
![4ADFD57E-BA91-4A6E-8B2A-D4EA29EB699D](https://user-images.githubusercontent.com/23158634/220020511-e9f22048-bb9d-456b-b03d-bd14fd46078f.jpeg)
 
![CBA659E3-010E-4711-B4EF-D8C138F853B2](https://user-images.githubusercontent.com/23158634/220020512-41bee4d9-01c9-4bf7-959c-add611a1e301.jpeg)

![2857B70E-9B59-40CD-9AE4-9CE41465786E](https://user-images.githubusercontent.com/23158634/220020485-973d15ec-1048-4c07-bf20-6635b6178181.jpeg)

**Comment by lukasa1993** [comment]
@jksmurf 
this commands are just shortcut what you'd type in `ssh` edit is extremely experimental and works on very limited files and systems, main usage for this is to move files on server side if you seek to edit files often better would be Termius which has IOS Files integration and then any text editor on iOS, as for VIEW should work which is basically `cat /path/to/file` if its binary it will fail but text files it must show easily, one more thing this can't escalate permissions meaning if user your logged in doesn't have access to file directly this won't `sudo` to try access so it will just do nothing

**Comment by jksmurf** [comment]
Hi thanks lukas I’m afraid that’s all way above my head. I’ll look for something else, it’s a pity - it had promise! Cheers k.

**Comment by lukasa1993** [comment]
> Hi thanks lukas I’m afraid that’s all way above my head. I’ll look for something else, it’s a pity - it had promise! Cheers k.

Termius and text editor with files integration will be way more user friendly then this just give it a shot
