### ISSUE TITLE
Public key support

### ISSUE THREAD

**Issue by fredldotme** [lukasa1993/scp-client#2]
What it says on the tin.
Support for public-private keys is a requirement in environments where password authentication is disabled.

I‘d propose adding the ability to import a key via iTunes or inside the app, generating new keys could be added later on.

Thank you again for this app.

**Comment by lukasa1993** [comment]
will add on next release

**Comment by fredldotme** [comment]
Thank you, any ETA?

**Comment by lukasa1993** [comment]
under appstore review probly tommorow

**Comment by fredldotme** [comment]
Mmm, that was quick, awesome!

**Comment by lukasa1993** [comment]
v1.2 is out please check if this feature doesnt work reopen new issue ill close this one
