### ISSUE TITLE
Files.app integration

### ISSUE THREAD

**Issue by fredldotme** [lukasa1993/scp-client#3]
This feature would allow to integrate SCP into the file browser shipped with iOS 11 and later.

Benefits:
- Copy and paste/move between storage providers (ie iCloud to SCP and back)
- Editing capabilities for-free (ie iWork documents open in Pages, Keynote, etc)

**Comment by fredldotme** [comment]
Apple documentation:
https://developer.apple.com/documentation/fileprovider

**Comment by fredldotme** [comment]
Example as implemented by Nextcloud:
https://github.com/nextcloud/ios/tree/master/File%20Provider%20Extension

**Comment by lukasa1993** [comment]
i had this originally planned but some ssh servers doesnt support scp, even now way this app works is thrue ssh commands run in shell so file edit is bit wierd since in order to edit file in this manner i need to send something like "" > file.txt and this will break some stuff like line endings probly can make it work with small files i am planning to do this still but for full edit this wont work. another way is to download whole file edit and upload thats also not sertenty thst will work in every case like my tv box has only vt100 profile and file trainster is an issue. so basicly i am considering this but cant promise anything

**Comment by fredldotme** [comment]
SCP is not suitable for „real“ synchronization like cloud storage and/or distributed protocols, so temporary download seems feasable enough for this kind of use case. For example, Pages probably implements the file down- and reupload while editing the document at hand, so the FileProvider implementation can act as a „dumb pipe“ for file transfer only.

**Comment by lukasa1993** [comment]
> SCP is not suitable for „real“ synchronization like cloud storage and/or distributed protocols, so temporary download seems feasable enough for this kind of use case. For example, Pages probably implements the file down- and reupload while editing the document at hand, so the FileProvider implementation can act as a „dumb pipe“ for file transfer only.

sure if download/upload works everywhere even without scp support on ssh servers this will be done. i need to test all that first

**Comment by fredldotme** [comment]
I‘d say it‘s safe to assume the server side has the proper components installed (sftp etc) as the end product reflects a similar end product as a FUSE-mounted sshfs, minus the random file access.

**Comment by lukasa1993** [comment]
no its not safe to assume that. my local server doesn’t support any of that. that was reason why i went with command execution and parsing

**Comment by fredldotme** [comment]
That‘s very weird but understandable.

**Comment by fredldotme** [comment]
Not to spam your inbox, but if you need someone to test a different approach/implementation I‘d be willing to help.

**Comment by lukasa1993** [comment]
sure, i also submitted testflight build when its approved on readme there will be a link so anyone can join testflight group

**Comment by fredldotme** [comment]
As for the possibility of adding proper SFTP support, I‘d suggest implementing both command- and SFTP-based transfer classes by inheriting the same interface class (I‘m not much of a Swift programmer, I do C++).

If you need a server in such a setup, please contact me directly: dev.beidl AT gmail.com

**Comment by lukasa1993** [comment]
quick edit on testflight now.

https://testflight.apple.com/join/ZqAD0ONr

**Comment by fredldotme** [comment]
The text editor control is not scaled properly to its container on iPad, but editing works.

**Comment by lukasa1993** [comment]
ui i just place holder atm, checking upload/donwload to make sure apple file integration will work

**Comment by amontilla0** [comment]
Hey @lukasa1993 

I was looking for apps with SCP support in iOS and found yours, thanks for your development! Exactly this iOS Files integration feature is what I would want right now since I’d like to download some time lapse pics / videos from a Raspberry Pi to my iPhone quick and easy.

Any luck with this issue? Would love to help.

Best,
Abe

**Comment by lukasa1993** [comment]
bit tricky to implememt way i have file listing atm couldn't sit down to do it first time will give another try at some point but needs time wich i dont yet have, will be there eventually

**Comment by amontilla0** [comment]
Okay, sounds good. Let me know if you need a hand!

**Comment by amontilla0** [comment]
Okay, sounds good. Let me know if you need a hand!

**Comment by nodecentral** [comment]
Just wanted to add my support to adding the ability to see my local ‘Files’ (iCloud/local) on one side and the remote location on the other. Killer feature if it could be added..

**Comment by lukasa1993** [comment]
> Just wanted to add my support to adding the ability to see my local ‘Files’ (iCloud/local) on one side and the remote location on the other. Killer feature if it could be added..

cant find proper SSH library for Swift/Objetive-c to implement that, one i use is total crap cant even reliably do file edits i tried multiple ones none of them delivered so still searching

**Comment by tanmaster** [comment]
I'd also love this feature!

**Comment by lukasa1993** [comment]
[Termius](https://apps.apple.com/ge/app/termius-terminal-ssh-client/id549039908) covered this, i am using it for this as well
