### ISSUE TITLE
Public- and private keys lost after closing

### ISSUE THREAD

**Issue by fredldotme** [lukasa1993/scp-client#4]
After closing the app all private and public keys are lost, requiring to manually add the keys back into the server configurations.

**Comment by lukasa1993** [comment]
hmm weird case keys are saved same way servers are, are servers deleted as well? or only keys ?

**Comment by lukasa1993** [comment]
very weird, i think system deletes values form keychain when it sees privkey and publickey very weird

**Comment by lukasa1993** [comment]
fixed. seek 1.3(324) on testflight
