### ISSUE TITLE
Feature request: Add ability to see hidden files and directories

### ISSUE THREAD

**Issue by TimofeyK** [lukasa1993/scp-client#5]
Hello!

I discovered this little gem when searching for an SSH client for iPhone that I needed for my Raspberry Pi. The app works very well but some of the files I need to see are located in hidden directories (such as .homebridge)

Please consider adding a switch for show/hide hidden files

**Comment by lukasa1993** [comment]
yes feature is coming. consider enrolling in testflight to test it first

**Comment by TimofeyK** [comment]
Thank you. Already using TestFlight version

**Comment by lukasa1993** [comment]
live on testflight

**Comment by TimofeyK** [comment]
Hidden folders cannot be navigated into, the app thinks they are files

**Comment by lukasa1993** [comment]
seems my folder detection needs improvements

**Comment by TimofeyK** [comment]
Updated to 1.3 (331), now hidden folders work correctly. Thank you!

**Comment by lukasa1993** [comment]
👍
