### ISSUE TITLE
Editor layout issue

### ISSUE THREAD

**Issue by TimofeyK** [lukasa1993/scp-client#7]
In Editor there is a layout issue: number of lines at the end are hidden behind the keyboard

You can pull and stretch the editor up swapping fingers to see what’s hidden but obviously can’t edit that part

On iPhone XS with standard text size there are 14 lines behind the standard keyboard

**Comment by lukasa1993** [comment]
must Be fixed in 338 build

**Comment by lukasa1993** [comment]
seems fixed reopen new one if not 👍
